<a href="https://colab.research.google.com/github/preetamjumech/truncated_svd_txta/blob/main/Preetam_Saha_09_10_2022_Movies_Compiled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams["figure.figsize"]=(20,10)

In [3]:
data = pd.read_csv("/content/drive/MyDrive/Movie_Compiled.csv")
data.head()

Rating           Date                                              Title  \
0         12 April 2012  An Unstoppable Force of Awesomeness! All Hail ...   
1         19 April 2012  They balanced everything masterfully. As Good ...   
2   10.0  20 April 2012                  The Avengers assembled flawlessly   
3    9.0  16 April 2012          LA Review of 'The Avengers' (No spoilers)   
4   10.0    2 July 2017  Bad-ass descent-amazing superhero MCU action f...   

                                              Review  
0  I have got to tell anyone who will listen that...  
1  If you're a fan of epic adventure movies, then...  
2  I'm sorry to say The Avengers isn't a good mov...  
3  LA Review of 'The Avengers' (No spoilers)\r\n\...  
4  Marvel's The Avengers (2012) is an awesome des...

In [5]:
data.shape

(4502, 4)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4502 entries, 0 to 4501
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Rating  4175 non-null   object
 1   Date    4502 non-null   object
 2   Title   4502 non-null   object
 3   Review  4402 non-null   object
dtypes: object(4)
memory usage: 140.8+ KB


In [7]:
data.Review

0       I have got to tell anyone who will listen that...
1       If you're a fan of epic adventure movies, then...
2       I'm sorry to say The Avengers isn't a good mov...
3       LA Review of 'The Avengers' (No spoilers)\r\n\...
4       Marvel's The Avengers (2012) is an awesome des...
                              ...                        
4497                                                  NaN
4498    "Ice Age" gives us a sabertooth tiger, a sloth...
4499    Ice Age was a very entertaining movie, with br...
4500    Ice Age, thats a good title. I was very confus...
4501    While most 3D films ("Toy Story", "Shrek" for ...
Name: Review, Length: 4502, dtype: object

In [9]:
import re

In [12]:
for i in data.Review[:20]:
  pat = re.findall(r"Permalink",i)
  print(pat)
  pat2 = re.findall(r"\d+ out of \d+ found this helpful",i)
  print(pat2)

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['Permalink']
['72 out of 112 found this helpful']
[]
[]
['Permalink']
['377 out of 667 found this helpful']
[]
[]
[]
[]
[]
[]
[]
[]
['Permalink']
['302 out of 589 found this helpful']
['Permalink']
['9 out of 12 found this helpful']
['Permalink']
['314 out of 623 found this helpful']
[]
[]
[]
[]
['Permalink']
['271 out of 547 found this helpful']
[]
[]
[]
[]


In [15]:
def clean_review(review):
  try:
    review = re.sub(r"Permalink","",review)
    review = re.sub(r"\d+ out of \d+ found this helpful","",review)
    return review
  except:
    pass

In [16]:
clean_review("hello how are you Permalink 12 out of 22 found this helpful be careful")

'hello how are you   be careful'

In [17]:
clean_review("Hello Permalink")

'Hello '

In [19]:
clean_review("I am 76 out of 23 found this helpful good")

'I am  good'

In [20]:
data_copy = data.copy()

In [21]:
data_copy["Review"] = data_copy["Review"].apply(clean_review)

In [22]:
data_copy.head()

Rating           Date                                              Title  \
0         12 April 2012  An Unstoppable Force of Awesomeness! All Hail ...   
1         19 April 2012  They balanced everything masterfully. As Good ...   
2   10.0  20 April 2012                  The Avengers assembled flawlessly   
3    9.0  16 April 2012          LA Review of 'The Avengers' (No spoilers)   
4   10.0    2 July 2017  Bad-ass descent-amazing superhero MCU action f...   

                                              Review  
0  I have got to tell anyone who will listen that...  
1  If you're a fan of epic adventure movies, then...  
2  I'm sorry to say The Avengers isn't a good mov...  
3  LA Review of 'The Avengers' (No spoilers)\r\n\...  
4  Marvel's The Avengers (2012) is an awesome des...

In [23]:
data_copy.isnull().sum()

Rating    327
Date        0
Title       0
Review    100
dtype: int64

In [26]:
for i in data_copy.Review:
  try:
    if re.findall(r"\d+ out of \d+ found this helpful",i):
      print(i)
    elif re.findall(r"Permalink",i):
      print(i)
    else:
      pass
  except:
    pass

In [28]:
data_copy[data_copy["Review"].isnull()]

Rating              Date  \
3555    4.0      14 June 2018   
3559    5.0       8 July 2018   
3562    8.0       9 July 2018   
3564   10.0       7 July 2018   
3567   10.0      16 June 2018   
...     ...               ...   
4461   10.0      3 April 2002   
4480   10.0     11 April 2002   
4485   10.0  12 December 2014   
4490   10.0   7 December 2006   
4497   10.0      7 April 2005   

                                                  Title Review  
3555                    Ten things about Fallen Kingdom   None  
3559                  This franchise should go extinct.   None  
3562              Fine movie but as fan Im still hungry   None  
3564                   Fun Movie - here is what you get   None  
3567        One button can change the (Jurassic) World!   None  
...                                                 ...    ...  
4461                               Weak and Predictable   None  
4480         All the great makings of an (ice) cool pic   None  
4485  Touch of Jungle Book and Monsters, Inc. but su...   None  
4490                                            Ice Age   None  
4497                                    The cute Factor   None  

[100 rows x 4 columns]

In [29]:
data_copy[data_copy["Review"].isnull()].value_counts()

Series([], dtype: int64)

In [31]:
data_rev=data_copy[~data_copy["Review"].isnull()]
data_rev.shape

(4402, 4)

In [32]:
data_rev.Rating.value_counts()

10.0    1143
1.0      719
9.0      428
8.0      301
7.0      288
6.0      252
5.0      232
3.0      225
2.0      218
4.0      202
          67
Name: Rating, dtype: int64

In [33]:
import numpy as np

In [38]:
data_rev1 = data_rev.replace(" ",np.nan)

In [39]:
data_rev1.head()

Rating           Date                                              Title  \
0    NaN  12 April 2012  An Unstoppable Force of Awesomeness! All Hail ...   
1    NaN  19 April 2012  They balanced everything masterfully. As Good ...   
2   10.0  20 April 2012                  The Avengers assembled flawlessly   
3    9.0  16 April 2012          LA Review of 'The Avengers' (No spoilers)   
4   10.0    2 July 2017  Bad-ass descent-amazing superhero MCU action f...   

                                              Review  
0  I have got to tell anyone who will listen that...  
1  If you're a fan of epic adventure movies, then...  
2  I'm sorry to say The Avengers isn't a good mov...  
3  LA Review of 'The Avengers' (No spoilers)\r\n\...  
4  Marvel's The Avengers (2012) is an awesome des...

In [41]:
data_rev1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4402 entries, 0 to 4501
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Rating  4008 non-null   object
 1   Date    4402 non-null   object
 2   Title   4402 non-null   object
 3   Review  4402 non-null   object
dtypes: object(4)
memory usage: 172.0+ KB


In [42]:
data_rev1["Rating"] = data_rev1["Rating"].apply(lambda x: float(x))

In [43]:
data_rev1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4402 entries, 0 to 4501
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Rating  4008 non-null   float64
 1   Date    4402 non-null   object 
 2   Title   4402 non-null   object 
 3   Review  4402 non-null   object 
dtypes: float64(1), object(3)
memory usage: 172.0+ KB


In [44]:
train_data = data_rev1[~data_rev1["Rating"].isnull()]
test_data = data_rev1[data_rev1["Rating"].isnull()]

In [45]:
train_data.shape, test_data.shape

((4008, 4), (394, 4))

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train, x_val , y_train, y_val = train_test_split(train_data.iloc[:,1:],
                                                   train_data.iloc[:,0],
                                                   test_size = 0.4,
                                                   random_state = 123456)
                                                   

In [59]:
x_val.shape

(1604, 3)

In [52]:
type(x_train)

pandas.core.frame.DataFrame

In [60]:
x_train.shape

(2404, 3)

In [53]:
type(y_train)

pandas.core.series.Series

In [49]:
from wordcloud import STOPWORDS

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [51]:
tfidf = TfidfVectorizer(token_pattern="[a-z']+",min_df=5,max_df=0.6,stop_words=STOPWORDS)

In [62]:
tfidf_mat_train = tfidf.fit_transform(x_train["Review"])
tfidf_mat_val = tfidf.transform(x_val["Review"])
tfidf_mat_test = tfidf.transform(test_data["Review"])

In [63]:
tfidf_mat_val.shape

(1604, 5945)

In [64]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import cohen_kappa_score

In [65]:
lr = LogisticRegression()

In [66]:
lr.fit(tfidf_mat_train,y_train)

LogisticRegression()

In [67]:
lr_pred = lr.predict(tfidf_mat_val)

In [68]:
cohen_kappa_score(lr_pred, y_val)

0.24551651948086373

In [98]:
lr_pred_test = lr.predict(tfidf_mat_test)

In [99]:
lr_pred_test

array([10., 10., 10., 10., 10., 10., 10., 10.,  9., 10., 10., 10., 10.,
       10.,  1., 10., 10., 10.,  1., 10.,  7., 10., 10., 10.,  1.,  1.,
        1.,  1.,  1.,  1.,  1., 10.,  1., 10.,  1., 10., 10., 10., 10.,
       10.,  1.,  1.,  1.,  4.,  1.,  1., 10.,  1.,  1., 10.,  7.,  1.,
       10.,  1., 10., 10.,  8., 10.,  7.,  1., 10.,  8., 10., 10.,  8.,
       10.,  7., 10., 10.,  1., 10., 10.,  8., 10., 10., 10., 10., 10.,
       10., 10.,  9., 10., 10., 10.,  7., 10.,  9., 10., 10., 10.,  1.,
       10., 10.,  1., 10.,  9., 10., 10.,  1.,  9.,  9., 10.,  8., 10.,
       10., 10., 10., 10., 10.,  8.,  7., 10.,  1., 10., 10., 10.,  9.,
       10., 10.,  9.,  9.,  1., 10., 10., 10.,  1., 10., 10., 10.,  9.,
       10., 10., 10.,  1., 10., 10.,  1.,  1., 10., 10., 10., 10., 10.,
       10., 10., 10.,  7., 10.,  1., 10., 10., 10.,  6.,  9.,  1., 10.,
       10., 10., 10., 10.,  9.,  9., 10., 10.,  1.,  9., 10., 10., 10.,
       10.,  1., 10.,  9., 10., 10., 10., 10., 10., 10.,  8., 10

In [69]:
gbm = GradientBoostingClassifier(learning_rate=0.01,n_estimators=500)

In [70]:
gbm.fit(tfidf_mat_train,y_train)

GradientBoostingClassifier(learning_rate=0.01, n_estimators=500)

In [72]:
gbm_pred = lr.predict(tfidf_mat_val)

In [73]:
cohen_kappa_score(gbm_pred, y_val)

0.24551651948086373

In [100]:
gbm_pred_test = gbm.predict(tfidf_mat_test)

In [101]:
gbm_pred_test

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10.,  1., 10., 10., 10.,  9.,  3., 10., 10., 10., 10., 10.,  9.,
        1.,  1.,  1.,  6.,  1., 10.,  1., 10.,  3., 10.,  5., 10., 10.,
       10.,  1.,  1.,  1.,  4.,  1.,  1., 10.,  1.,  1., 10.,  1.,  4.,
       10.,  5., 10., 10.,  7., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10.,  9., 10.,  8.,  9.,  9.,  8., 10.,  9., 10., 10., 10.,
        8.,  8.,  1., 10., 10., 10.,  4.,  8., 10., 10., 10., 10.,  9.,
       10., 10.,  7., 10., 10., 10., 10., 10.,  2., 10., 10.,  7., 10.,
       10.,  9., 10., 10., 10.,  8.,  1.,  5., 10., 10., 10., 10., 10.,
       10., 10., 10., 10.,  9., 10.,  8.,  8.,  1., 10., 10.,  2., 10.,
       10.,  3., 10.,  7., 10.,  9., 10.,  5.,  6., 10., 10., 10., 10.,
       10.,  3.,  9.,  4.,  1.,  1., 10., 10.,  8., 10., 10., 10.,  8.,
        8., 10., 10.,  7., 10.,  9.,  7.,  1.,  1., 10., 10.,  9., 10.,
        7.,  1., 10.,  9.,  9., 10.,  1., 10., 10., 10.,  7., 10

In [74]:
from sklearn.decomposition import TruncatedSVD

In [75]:
svd_new = TruncatedSVD(n_components=200)

In [76]:
word_vec = svd_new.fit_transform(tfidf_mat_train.T)

In [77]:
word_vec.shape

(5945, 200)

In [78]:
tfidf.vocabulary_

{'will': 5832,
 'win': 5836,
 'oscar': 3700,
 'worst': 5898,
 'scenario': 4565,
 'director': 1464,
 'godfather': 2297,
 'probably': 4038,
 'perfect': 3819,
 'made': 3180,
 'strong': 5074,
 'plot': 3915,
 'unique': 5593,
 'cast': 757,
 'direction': 1461,
 'filming': 2043,
 'editing': 1649,
 'beyond': 504,
 'words': 5884,
 'music': 3475,
 'makes': 3196,
 'blend': 533,
 'great': 2343,
 'movies': 3449,
 'course': 1167,
 'lack': 2957,
 'one': 3664,
 'two': 5537,
 'things': 5328,
 'mentioned': 3313,
 'difficult': 1442,
 'match': 3255,
 'francis': 2163,
 'coppola': 1126,
 'part': 3779,
 'ii': 2612,
 'may': 3272,
 'masterpiece': 3252,
 'watch': 5768,
 'never': 3533,
 'bored': 581,
 'always': 176,
 'surprised': 5181,
 'wonderful': 5874,
 'see': 4624,
 'young': 5931,
 'al': 143,
 'pacino': 3742,
 'change': 798,
 'college': 951,
 'boy': 600,
 'ruthless': 4502,
 'making': 3198,
 'even': 1798,
 'marlon': 3234,
 'brando': 607,
 'title': 5401,
 'role': 4457,
 'albeit': 147,
 'small': 4843,
 'underrat

In [80]:
tfidf.vocabulary_["hulk"]

2574

In [90]:
word_vec

array([[ 0.15341444, -0.02463582, -0.02718272, ...,  0.00109419,
        -0.05065349, -0.02814008],
       [ 0.00989461, -0.00480574, -0.00755533, ...,  0.00148157,
        -0.00720812, -0.00596217],
       [ 0.03564646,  0.00441864,  0.01405929, ..., -0.00951835,
        -0.03433283,  0.01355871],
       ...,
       [ 0.11525088, -0.05926002, -0.07436446, ..., -0.00868813,
        -0.07356336, -0.00358733],
       [ 0.05436367, -0.03157827, -0.04066125, ..., -0.00594533,
         0.00352116,  0.01537471],
       [ 0.02564565, -0.01302981, -0.00806254, ...,  0.00934437,
        -0.00089071,  0.00172797]])

In [ ]:
word_vec[2574,:].reshape(1,-1)

In [82]:
from sklearn.metrics import pairwise_distances

In [92]:
dist_hulk = pairwise_distances(X=word_vec,Y=word_vec[2574,:].reshape(1,-1),metric = "cosine")

In [93]:
dist_hulk.flatten().argsort()

array([2574, 5337, 2812, ..., 3583, 2269, 1602])

In [94]:
id_to_word = { v:k for k,v in tfidf.vocabulary_.items()}

In [96]:
id_to_word[5337]

'thor'

In [97]:
id_to_word[2812]

'iron'