In [1]:
import pandas as pd

In [ ]:
#https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [2]:
data = pd.read_csv("IMDB Dataset.csv")
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
data.shape

(50000, 2)

In [4]:
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import cohen_kappa_score

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [8]:
target = {"positive":1,"negative":0}

In [9]:
data["sentiment"] = data["sentiment"].map(target)

In [10]:
data.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 781.4+ KB


In [11]:
x_train, x_test, y_train, y_test = train_test_split(data["review"],data["sentiment"],test_size=0.3,random_state=123456)

In [12]:
x_train.shape

(35000,)

In [13]:
x_test.shape

(15000,)

In [14]:
y_train.shape

(35000,)

In [16]:
y_train[:5]

2428     1
31331    0
37927    1
39000    0
16839    1
Name: sentiment, dtype: int64

In [18]:
from wordcloud import STOPWORDS

In [19]:
tfidf = TfidfVectorizer(token_pattern="[a-z']+",max_df=0.6,min_df=10,stop_words=STOPWORDS)

In [22]:
tfidf_mat_train = tfidf.fit_transform(x_train)
tfidf_mat_val = tfidf.transform(x_test)

In [23]:
tfidf_mat_train.shape

(35000, 22074)

In [35]:
tfidf_mat_train

<35000x22074 sparse matrix of type '<class 'numpy.float64'>'
	with 3197433 stored elements in Compressed Sparse Row format>

In [24]:
tfidf_mat_val.shape

(15000, 22074)

In [25]:
lr = LogisticRegression()

In [26]:
lr.fit(tfidf_mat_train,y_train)

LogisticRegression()

In [28]:
pred = lr.predict(tfidf_mat_val)

In [29]:
pred

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [31]:
cohen_kappa_score(pred,y_test)

0.7860228470538773

# SVD

In [32]:
svd_new = TruncatedSVD(n_components=200)

In [36]:
word_vec = svd_new.fit_transform(tfidf_mat_train.T)

In [37]:
word_vec.shape

(22074, 200)

In [38]:
tfidf.vocabulary_

{'totally': 20051,
 'surprised': 19217,
 'good': 8404,
 'actually': 262,
 'first': 7463,
 'saw': 17019,
 'mildly': 12477,
 'amused': 726,
 'must': 12972,
 'say': 17024,
 'still': 18757,
 'disappointed': 5552,
 'donald': 5828,
 "o'connor": 13461,
 'given': 8290,
 'bigger': 1923,
 'better': 1893,
 'role': 16657,
 'enormous': 6564,
 'talent': 19431,
 'br': 2347,
 'great': 8555,
 'chemistry': 3295,
 'among': 713,
 'main': 11869,
 'cast': 3006,
 'members': 12325,
 'matthau': 12164,
 'never': 13206,
 'funnier': 7974,
 'tremendously': 20238,
 'glad': 8293,
 'picture': 14532,
 'got': 8444,
 'made': 11820,
 'see': 17275,
 'lemmon': 11289,
 'team': 19534,
 'last': 11143,
 'time': 19899,
 'vehicle': 21003,
 'puts': 15492,
 'use': 20891,
 'brent': 2431,
 'proves': 15343,
 'data': 4910,
 'star': 18625,
 'trek': 20234,
 'next': 13231,
 'character': 3194,
 'play': 14658,
 'storyline': 18828,
 'really': 15797,
 'quite': 15559,
 'simple': 17791,
 'comedy': 3810,
 'characters': 3205,
 'work': 21819,
 'w

In [39]:
tfidf.vocabulary_["jurassic"]

10749

In [40]:
from sklearn.metrics import pairwise_distances

In [41]:
word_vec[10749,:].reshape(-1,1)

array([[ 4.84664430e-02],
       [ 1.14766511e-04],
       [-2.14200915e-02],
       [ 1.88513139e-02],
       [ 3.01173993e-04],
       [-9.02447774e-03],
       [ 2.36902669e-03],
       [ 1.33684576e-02],
       [ 8.71754517e-03],
       [-4.80361871e-03],
       [ 4.12625666e-04],
       [-5.19499126e-03],
       [-1.28824788e-02],
       [-6.94798003e-03],
       [ 2.72762346e-03],
       [-3.12394874e-02],
       [ 1.12983573e-03],
       [-1.26981925e-02],
       [ 1.21101165e-02],
       [ 1.61198952e-02],
       [ 1.94272687e-03],
       [ 5.21492801e-03],
       [ 1.38528496e-02],
       [-1.67919004e-02],
       [-1.28452259e-02],
       [ 1.05723663e-02],
       [ 9.22853909e-04],
       [-5.47612258e-03],
       [-1.05173779e-02],
       [-2.84643530e-02],
       [ 2.31746577e-02],
       [-5.48740341e-03],
       [ 1.46384718e-02],
       [-1.62100281e-02],
       [ 9.07890015e-03],
       [-4.08822843e-03],
       [-2.18345793e-02],
       [-1.27780269e-02],
       [-2.8

In [42]:
word_vec[10749,:].reshape(1,-1)

array([[ 4.84664430e-02,  1.14766511e-04, -2.14200915e-02,
         1.88513139e-02,  3.01173993e-04, -9.02447774e-03,
         2.36902669e-03,  1.33684576e-02,  8.71754517e-03,
        -4.80361871e-03,  4.12625666e-04, -5.19499126e-03,
        -1.28824788e-02, -6.94798003e-03,  2.72762346e-03,
        -3.12394874e-02,  1.12983573e-03, -1.26981925e-02,
         1.21101165e-02,  1.61198952e-02,  1.94272687e-03,
         5.21492801e-03,  1.38528496e-02, -1.67919004e-02,
        -1.28452259e-02,  1.05723663e-02,  9.22853909e-04,
        -5.47612258e-03, -1.05173779e-02, -2.84643530e-02,
         2.31746577e-02, -5.48740341e-03,  1.46384718e-02,
        -1.62100281e-02,  9.07890015e-03, -4.08822843e-03,
        -2.18345793e-02, -1.27780269e-02, -2.85778043e-03,
         2.71471286e-03, -7.22573595e-05, -9.89301862e-03,
         1.14259726e-03,  2.77261662e-03,  1.62988745e-03,
        -6.34088961e-03,  1.10204305e-02, -6.70332201e-03,
         6.32842055e-03, -4.96331987e-03, -3.62246987e-0

In [44]:
dist_jurassic = pairwise_distances(word_vec,word_vec[10749,:].reshape(1,-1),metric="cosine")

In [45]:
dist_jurassic.shape

(22074, 1)

In [46]:
dist_jurassic

array([[1.01577823],
       [0.86800195],
       [0.9124316 ],
       ...,
       [0.84924926],
       [0.88999816],
       [0.95054046]])

In [47]:
dist_jurassic.flatten()

array([1.01577823, 0.86800195, 0.9124316 , ..., 0.84924926, 0.88999816,
       0.95054046])

In [48]:
dist_jurassic.flatten().argsort()

array([10749,  5511,  5510, ..., 12346, 21098, 10477], dtype=int64)

In [49]:
id_word = {v:k for k,v in tfidf.vocabulary_.items()}

In [50]:
id_word

{20051: 'totally',
 19217: 'surprised',
 8404: 'good',
 262: 'actually',
 7463: 'first',
 17019: 'saw',
 12477: 'mildly',
 726: 'amused',
 12972: 'must',
 17024: 'say',
 18757: 'still',
 5552: 'disappointed',
 5828: 'donald',
 13461: "o'connor",
 8290: 'given',
 1923: 'bigger',
 1893: 'better',
 16657: 'role',
 6564: 'enormous',
 19431: 'talent',
 2347: 'br',
 8555: 'great',
 3295: 'chemistry',
 713: 'among',
 11869: 'main',
 3006: 'cast',
 12325: 'members',
 12164: 'matthau',
 13206: 'never',
 7974: 'funnier',
 20238: 'tremendously',
 8293: 'glad',
 14532: 'picture',
 8444: 'got',
 11820: 'made',
 17275: 'see',
 11289: 'lemmon',
 19534: 'team',
 11143: 'last',
 19899: 'time',
 21003: 'vehicle',
 15492: 'puts',
 20891: 'use',
 2431: 'brent',
 15343: 'proves',
 4910: 'data',
 18625: 'star',
 20234: 'trek',
 13231: 'next',
 3194: 'character',
 14658: 'play',
 18828: 'storyline',
 15797: 'really',
 15559: 'quite',
 17791: 'simple',
 3810: 'comedy',
 3205: 'characters',
 21819: 'work',
 21

In [51]:
id_word[5511]

'dinosaurs'

In [52]:
id_word[5510]

'dinosaur'